name: tp0
services:
  server:
    container_name: server
    image: server:latest
    user: 1000:1000
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini:ro
  client1:
    image: client:latest
    container_name: client1
    entrypoint: /client
    user: 1000:1000
    networks:
    - testing_net
    environment:
    - CLI_ID=1
    volumes:
    - ./data/client1:/app/data
    - ./client/config.yaml:/config.yaml:ro
    depends_on:
    - server
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
