name: tp0
services:
  server:
    container_name: server
    image: server:latest
    user: 1000:1000
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    networks:
    - testing-net
    volumes:
    - ./server/config.ini:/config.ini:ro
networks:
  testing-net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
